services:
  - type: web
    name: kingest-api
    runtime: node
    region: frankfurt
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PK
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_SECRET
        sync: false
